name: Linting
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: '[CHECKOUT] Checkout branch that triggered this workflow'
      uses: actions/checkout@v1

    - name: '[TOOLCHAIN] Set up Ruby 2.6'
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x


    - name: '[TOOLCHAIN] Install Asciidoctor and Asciidoctor PDF'
      run: gem install asciidoctor

    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      with:
      # Optional
        styles: |
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

      # Optional
        config: https://github.com/uyuni-project/uyuni-docs/blob/vale-style-checks-prototype/.github/.vale.ini

      # Optional
        files: modules/administration/pages
      env:
      # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

