name: Linting
on: [push]
jobs:
  prose:
    runs-on: ubuntu-latest

    steps:
    - name: '[CHECKOUT] Checkout branch that triggered this workflow'
      uses: actions/checkout@v2

    - name: 'Set up Ruby 2.6'
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: 'Install Asciidoctor'
      run: gem install asciidoctor
    - name: 'Print Working Directory'
      run: pwd

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Run vale for docs linting
      run: |
        brew install vale
        vale --debug modules/

